name: solar_system
description: A solar system simulator.
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.9.2
dependencies:
  forui: ^0.16.0 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  path_provider: ^2.1.3
  path:
  flutter_native_splash: ^2.4.1
  package_info_plus: ^9.0.0
  font_awesome_flutter: ^10.7.0
  faker: ^2.2.0
  navigation_builder: ^0.0.4
  objectbox: ^5.0.0
  objectbox_generator: ^5.0.0
  objectbox_flutter_libs: ^5.0.0
  equatable: 
  spark:
    path: C://Users//Adn//CascadeProjects//spark
flutter:
  uses-material-design: true
