name: solar_system
description: A solar system simulator.
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.10.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0
  flutter_native_splash: ^2.4.7
  font_awesome_flutter: ^10.12.0
  faker: ^2.2.0
  go_router: ^17.0.0
  manager:
    path: D://projects//manager
flutter:
  uses-material-design: true
